# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbl', models.CharField(max_length=32, verbose_name='label')),
                ('clr', models.PositiveIntegerField(verbose_name='color')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('lbl', models.CharField(max_length=256, verbose_name='label')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.Category')),
            ],
        ),
    ]
